### ISSUE TITLE
Switch to Start/End dates

### ISSUE THREAD

**Issue by mattkleker** [mattkleker/accounting-app#9]
Rather than always starting with tomorrow's date, I'd like to introduce the concept of a start and end date that will default to start=tomorrow and end=end of month.  

I added this: https://www.npmjs.com/package/ember-cli-bootstrap-datepicker

@samselikoff - the docs just say to use ```value=expiresAt``` but I'd like the default to be tomorrow.  I can add a date string like ```"12/13/14"``` but can't figure out how to make a dynamic default date.  Thoughts?

**Comment by mattkleker** [comment]
@samselikoff check it out

I implemented this, which added a bunch of possible cases because we don't prorate by the absolute number of days between the start and end dates, but rather by number of days in a given month.  i.e. prorating x from Jan 31 to Feb 2 means ```(x / 31 * 1) + (x / 28 * 2)```, not ```x / 365 * 3```

I've got most of it working the way I want it (but planning to change the layout).  The only issue I'm having is setting the end date to the end of next month if the start date is after the 17th.  I've tried this: 

```
//components/prorated-amount.js
  endDateSetter: function() {
    if (this.get('startDate').date() > 17) {
      this.set('end', moment().add(1, "month").endOf("month").format('MM/DD/YYYY'));
    }
      this.set('end', moment().endOf("month").format('MM/DD/YYYY'));
    }.on('init').property('startDate'),  
```

This makes the end date not initialize.  I tried switching to ```.property('startDate').on('init')```, but that makes it blow up completely.  

I also tried setting a local date variable like this: 

```
  endDateSetter: function() {
    var today = moment();
    if (today.date() > 17 ) {
..
```

I don't know why but this never got caught by the if statement, even when I did ```var today = moment("2014-01-18")```

I feel like I'm missing something obvious, but not sure what.  

You'll be happy to know that all changes to start/end dates were 100% test driven development :)

**Comment by samselikoff** [comment]
Hopefully I'll have some time to look at this today, could you push your commits?

**Comment by samselikoff** [comment]
Ah, I see. `.property` means computed property, so the function really represents a *value* that gets recomputed every time its dependencies (what you put in the `( )`) change. 

`.on('init')` means, invoke this function when the `init` action occurs. So you don't want to combine `.on` and `.property` declarations to a function, because `.property` really transforms the function into a computed value, whereas `.on` just says, invoke the function when a certain action occurs.

What you want is this:

```js
endDateSetter: function() {
}.on('init').observes('startDate'), 
```

That way the function is invoked on init, and also whenever `startDate` changes.
